# Use this by copying it to ~/.config/helix/config.toml

theme = "catppuccin-macchiato"

[editor]
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true