# Use this by copying it to ~/.config/helix/config.toml

theme = "catppuccin_macchiato"

[editor]
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false  # Don't ignore hidden files

[editor.soft-wrap]
enable = true

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
